/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as MobileVerifyRouteImport } from './routes/mobile-verify'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnalysisIndexRouteImport } from './routes/_authenticated/analysis/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedApiDocsIndexRouteImport } from './routes/_authenticated/api-docs/index'
import { Route as AuthenticatedApiKeysIndexRouteImport } from './routes/_authenticated/api-keys/index'
import { Route as AuthenticatedBatchIndexRouteImport } from './routes/_authenticated/batch/index'
import { Route as AuthenticatedExportIndexRouteImport } from './routes/_authenticated/export/index'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedIntegrationIndexRouteImport } from './routes/_authenticated/integration/index'
import { Route as AuthenticatedKycIndexRouteImport } from './routes/_authenticated/kyc/index'
import { Route as AuthenticatedLivenessIndexRouteImport } from './routes/_authenticated/liveness/index'
import { Route as AuthenticatedRulesEngineIndexRouteImport } from './routes/_authenticated/rules-engine/index'
import { Route as AuthenticatedRulesIndexRouteImport } from './routes/_authenticated/rules/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileVerifyRoute = MobileVerifyRouteImport.update({
  id: '/mobile-verify',
  path: '/mobile-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysisIndexRoute =
  AuthenticatedAnalysisIndexRouteImport.update({
    id: '/analysis/',
    path: '/analysis/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiDocsIndexRoute =
  AuthenticatedApiDocsIndexRouteImport.update({
    id: '/api-docs/',
    path: '/api-docs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiKeysIndexRoute =
  AuthenticatedApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBatchIndexRoute = AuthenticatedBatchIndexRouteImport.update({
  id: '/batch/',
  path: '/batch/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportIndexRoute =
  AuthenticatedExportIndexRouteImport.update({
    id: '/export/',
    path: '/export/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationIndexRoute =
  AuthenticatedIntegrationIndexRouteImport.update({
    id: '/integration/',
    path: '/integration/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKycIndexRoute = AuthenticatedKycIndexRouteImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivenessIndexRoute =
  AuthenticatedLivenessIndexRouteImport.update({
    id: '/liveness/',
    path: '/liveness/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRulesEngineIndexRoute =
  AuthenticatedRulesEngineIndexRouteImport.update({
    id: '/rules-engine/',
    path: '/rules-engine/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRulesIndexRoute = AuthenticatedRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/mobile-verify': typeof MobileVerifyRoute
  '/analysis/': typeof AuthenticatedAnalysisIndexRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/api-docs/': typeof AuthenticatedApiDocsIndexRoute
  '/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/batch/': typeof AuthenticatedBatchIndexRoute
  '/export/': typeof AuthenticatedExportIndexRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/integration/': typeof AuthenticatedIntegrationIndexRoute
  '/kyc/': typeof AuthenticatedKycIndexRoute
  '/liveness/': typeof AuthenticatedLivenessIndexRoute
  '/rules-engine/': typeof AuthenticatedRulesEngineIndexRoute
  '/rules/': typeof AuthenticatedRulesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/mobile-verify': typeof MobileVerifyRoute
  '/': typeof AuthenticatedIndexRoute
  '/analysis': typeof AuthenticatedAnalysisIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/api-docs': typeof AuthenticatedApiDocsIndexRoute
  '/api-keys': typeof AuthenticatedApiKeysIndexRoute
  '/batch': typeof AuthenticatedBatchIndexRoute
  '/export': typeof AuthenticatedExportIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/integration': typeof AuthenticatedIntegrationIndexRoute
  '/kyc': typeof AuthenticatedKycIndexRoute
  '/liveness': typeof AuthenticatedLivenessIndexRoute
  '/rules-engine': typeof AuthenticatedRulesEngineIndexRoute
  '/rules': typeof AuthenticatedRulesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/mobile-verify': typeof MobileVerifyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/analysis/': typeof AuthenticatedAnalysisIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/api-docs/': typeof AuthenticatedApiDocsIndexRoute
  '/_authenticated/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/_authenticated/batch/': typeof AuthenticatedBatchIndexRoute
  '/_authenticated/export/': typeof AuthenticatedExportIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/integration/': typeof AuthenticatedIntegrationIndexRoute
  '/_authenticated/kyc/': typeof AuthenticatedKycIndexRoute
  '/_authenticated/liveness/': typeof AuthenticatedLivenessIndexRoute
  '/_authenticated/rules-engine/': typeof AuthenticatedRulesEngineIndexRoute
  '/_authenticated/rules/': typeof AuthenticatedRulesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mobile-verify'
    | '/analysis/'
    | '/analytics/'
    | '/api-docs/'
    | '/api-keys/'
    | '/batch/'
    | '/export/'
    | '/history/'
    | '/integration/'
    | '/kyc/'
    | '/liveness/'
    | '/rules-engine/'
    | '/rules/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mobile-verify'
    | '/'
    | '/analysis'
    | '/analytics'
    | '/api-docs'
    | '/api-keys'
    | '/batch'
    | '/export'
    | '/history'
    | '/integration'
    | '/kyc'
    | '/liveness'
    | '/rules-engine'
    | '/rules'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/mobile-verify'
    | '/_authenticated/'
    | '/_authenticated/analysis/'
    | '/_authenticated/analytics/'
    | '/_authenticated/api-docs/'
    | '/_authenticated/api-keys/'
    | '/_authenticated/batch/'
    | '/_authenticated/export/'
    | '/_authenticated/history/'
    | '/_authenticated/integration/'
    | '/_authenticated/kyc/'
    | '/_authenticated/liveness/'
    | '/_authenticated/rules-engine/'
    | '/_authenticated/rules/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MobileVerifyRoute: typeof MobileVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-verify': {
      id: '/mobile-verify'
      path: '/mobile-verify'
      fullPath: '/mobile-verify'
      preLoaderRoute: typeof MobileVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis/': {
      id: '/_authenticated/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AuthenticatedAnalysisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-docs/': {
      id: '/_authenticated/api-docs/'
      path: '/api-docs'
      fullPath: '/api-docs/'
      preLoaderRoute: typeof AuthenticatedApiDocsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys/': {
      id: '/_authenticated/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof AuthenticatedApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batch/': {
      id: '/_authenticated/batch/'
      path: '/batch'
      fullPath: '/batch/'
      preLoaderRoute: typeof AuthenticatedBatchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export/': {
      id: '/_authenticated/export/'
      path: '/export'
      fullPath: '/export/'
      preLoaderRoute: typeof AuthenticatedExportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integration/': {
      id: '/_authenticated/integration/'
      path: '/integration'
      fullPath: '/integration/'
      preLoaderRoute: typeof AuthenticatedIntegrationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc/': {
      id: '/_authenticated/kyc/'
      path: '/kyc'
      fullPath: '/kyc/'
      preLoaderRoute: typeof AuthenticatedKycIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liveness/': {
      id: '/_authenticated/liveness/'
      path: '/liveness'
      fullPath: '/liveness/'
      preLoaderRoute: typeof AuthenticatedLivenessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules-engine/': {
      id: '/_authenticated/rules-engine/'
      path: '/rules-engine'
      fullPath: '/rules-engine/'
      preLoaderRoute: typeof AuthenticatedRulesEngineIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules/': {
      id: '/_authenticated/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof AuthenticatedRulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnalysisIndexRoute: typeof AuthenticatedAnalysisIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedApiDocsIndexRoute: typeof AuthenticatedApiDocsIndexRoute
  AuthenticatedApiKeysIndexRoute: typeof AuthenticatedApiKeysIndexRoute
  AuthenticatedBatchIndexRoute: typeof AuthenticatedBatchIndexRoute
  AuthenticatedExportIndexRoute: typeof AuthenticatedExportIndexRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
  AuthenticatedIntegrationIndexRoute: typeof AuthenticatedIntegrationIndexRoute
  AuthenticatedKycIndexRoute: typeof AuthenticatedKycIndexRoute
  AuthenticatedLivenessIndexRoute: typeof AuthenticatedLivenessIndexRoute
  AuthenticatedRulesEngineIndexRoute: typeof AuthenticatedRulesEngineIndexRoute
  AuthenticatedRulesIndexRoute: typeof AuthenticatedRulesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnalysisIndexRoute: AuthenticatedAnalysisIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedApiDocsIndexRoute: AuthenticatedApiDocsIndexRoute,
  AuthenticatedApiKeysIndexRoute: AuthenticatedApiKeysIndexRoute,
  AuthenticatedBatchIndexRoute: AuthenticatedBatchIndexRoute,
  AuthenticatedExportIndexRoute: AuthenticatedExportIndexRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
  AuthenticatedIntegrationIndexRoute: AuthenticatedIntegrationIndexRoute,
  AuthenticatedKycIndexRoute: AuthenticatedKycIndexRoute,
  AuthenticatedLivenessIndexRoute: AuthenticatedLivenessIndexRoute,
  AuthenticatedRulesEngineIndexRoute: AuthenticatedRulesEngineIndexRoute,
  AuthenticatedRulesIndexRoute: AuthenticatedRulesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MobileVerifyRoute: MobileVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
